//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lssCore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcctRec
    {
        public long Id { get; set; }
        public string DocType { get; set; }
        public decimal OpenAmount { get; set; }
        public System.DateTime DiscountDueDate { get; set; }
        public System.DateTime GLDate { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long DocNumber { get; set; }
        public string Remarks { get; set; }
        public string NetTerms { get; set; }
        public long AddressId { get; set; }
    }
}
